export const badges = [
  { name: "Outstanding Attendance", icon: "fa-calendar-check" },
  { name: "Team Player", icon: "fa-users" },
  { name: "Top Performer", icon: "fa-trophy" },
  { name: "Creative Thinker", icon: "fa-lightbulb" },
  { name: "Leadership Excellence", icon: "fa-crown" },
  { name: "Most Improved", icon: "fa-chart-line" },
  { name: "Best Presentation", icon: "fa-microphone" },
  { name: "Class Participation", icon: "fa-hand-paper" },
  { name: "Homework Hero", icon: "fa-book" },
  { name: "Positive Attitude", icon: "fa-smile" },
  { name: "Exemplary Behavior", icon: "fa-star" },
  { name: "Punctuality Award", icon: "fa-clock" },
  { name: "Collaboration Royalty", icon: "fa-hands-helping" },
  { name: "Academic Excellence", icon: "fa-graduation-cap" },
  { name: "Problem Solver", icon: "fa-puzzle-piece" },
  { name: "Mentor Award ", icon: "fa-chalkboard-teacher" },
  { name: "Sportsmanship", icon: "fa-running" },
  { name: "Innovation Award", icon: "fa-rocket" },
  { name: "Tech Savvy", icon: "fa-laptop-code" },
  { name: "Community Helper", icon: "fa-handshake" },
  { name: "Team Spirit", icon: "fa-heart" },
  { name: "Best Presenter", icon: "fa-user-tie" },
  { name: "Green Thumb", icon: "fa-leaf" },
  { name: "Artistic Talent", icon: "fa-palette" },
  { name: "Literary Genius", icon: "fa-book" },
  { name: "Science Whiz", icon: "fa-atom" },
  { name: "Mathematical Mind", icon: "fa-calculator" },
  { name: "Most Enthusiastic", icon: "fa-grin-stars" },
  { name: "Critical Thinker ", icon: "fa-brain" },
  { name: "Diligent Researcher ", icon: "fa-search" },
];
